# Generated by Django 6.0.6 on 2026-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='provider',
            field=models.CharField(choices=[('django.db.backends.postgresql', 'PostgreSQL'), ('django.db.backends.mysql', 'MariaDB/MySQL'), ('django.db.backends.sqlite3', 'SQLite3')], default='django.db.backends.postgresql', max_length=50),
        ),
    ]
