# Generated by Django 6.0.6 on 2026-06-14 11:18

import Databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0002_alter_database_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AddField(
            model_name='database',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a .db file (required for SQLite3).', null=True, upload_to=Databases.models.database_file_upload_path),
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='database',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
