# Generated by Django 6.0.6 on 2026-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0003_delete_provider_database_file_alter_database_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='db_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
