# Generated by Django 6.0.6 on 2026-06-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0006_alter_database_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('disconnected', 'Disconnected')], default='unknown', max_length=20),
        ),
    ]
